'use client';

import { useState, useEffect, useRef } from 'react';
import { slugify } from '@/lib/slugify';

interface SlugInputProps {
  name?: string;
  defaultValue?: string;
  /** Controlled value. When provided, the parent owns the slug state. */
  value?: string;
  /** Controlled auto-generated flag (only meaningful when `value` is provided). */
  autoGenerated?: boolean;
  placeholder?: string;
  className?: string;
  sourceName?: string; // name of the input to derive slug from (uncontrolled mode only)
  /** Called whenever the effective slug changes (manual edit or auto-generated). */
  onChange?: (value: string) => void;
}

export function SlugInput({
  name = 'slug',
  defaultValue = '',
  value,
  autoGenerated: autoGeneratedProp,
  placeholder = 'slug',
  className = 'w-40 rounded-lg border px-3 py-2 text-sm',
  sourceName = 'name',
  onChange,
}: SlugInputProps) {
  const isControlled = value !== undefined;
  const [internalValue, setInternalValue] = useState(defaultValue);
  const [internalAutoGenerated, setInternalAutoGenerated] = useState(!defaultValue);

  const currentValue = isControlled ? value : internalValue;
  const autoGenerated = isControlled ? (autoGeneratedProp ?? false) : internalAutoGenerated;

  // Keep the latest onChange without re-binding the form event listeners
  // (onChange is re-created on every parent render). Updated in an effect,
  // not during render, per React's rules for refs.
  const onChangeRef = useRef(onChange);

  useEffect(() => {
    onChangeRef.current = onChange;
  }, [onChange]);

  // Auto-generate the slug from the source field via a native form listener.
  // Controlled mode (parent owns the slug) skips this entirely — the parent
  // derives the slug inside its own React onChange handler so it stays batched
  // with the name update and never re-renders the name input with a stale value.
  useEffect(() => {
    if (isControlled || !autoGenerated || !sourceName) return;

    function handleInput(e: Event) {
      const input = e.target as HTMLInputElement;
      if (input.name === sourceName) {
        const slug = slugify(input.value);
        setInternalValue(slug);
        onChangeRef.current?.(slug);
      }
    }

    // Listen for input events on the source field in the same form
    const forms = document.querySelectorAll('form');
    const cleanup: (() => void)[] = [];

    forms.forEach((form) => {
      form.addEventListener('input', handleInput);
      cleanup.push(() => form.removeEventListener('input', handleInput));
    });

    return () => cleanup.forEach((fn) => fn());
  }, [isControlled, autoGenerated, sourceName]);

  return (
    <div className="relative">
      <input
        name={name}
        value={currentValue}
        onChange={(e) => {
          const next = e.target.value;
          if (!isControlled) setInternalValue(next);
          setInternalAutoGenerated(false);
          onChangeRef.current?.(next);
        }}
        placeholder={placeholder}
        className={className}
      />
      {autoGenerated && currentValue && (
        <span className="absolute -bottom-4 left-0 text-[10px] text-muted">auto-generated</span>
      )}
    </div>
  );
}
