'use client';

import { useState, useEffect } from 'react';

interface SlugInputProps {
  name?: string;
  defaultValue?: string;
  placeholder?: string;
  className?: string;
  sourceName?: string; // name of the input to derive slug from
}

export function SlugInput({
  name = 'slug',
  defaultValue = '',
  placeholder = 'slug',
  className = 'w-40 rounded-lg border px-3 py-2 text-sm',
  sourceName = 'name',
}: SlugInputProps) {
  const [value, setValue] = useState(defaultValue);
  const [autoGenerated, setAutoGenerated] = useState(!defaultValue);

  useEffect(() => {
    if (!autoGenerated || !sourceName) return;

    function handleInput(e: Event) {
      const input = e.target as HTMLInputElement;
      if (input.name === sourceName) {
        const slug = input.value
          .toLowerCase()
          .replace(/[^a-z0-9\s-]/g, '')
          .trim()
          .replace(/\s+/g, '-')
          .replace(/-+/g, '-');
        setValue(slug);
      }
    }

    // Listen for input events on the source field in the same form
    const forms = document.querySelectorAll('form');
    const cleanup: (() => void)[] = [];

    forms.forEach((form) => {
      form.addEventListener('input', handleInput);
      cleanup.push(() => form.removeEventListener('input', handleInput));
    });

    return () => cleanup.forEach((fn) => fn());
  }, [autoGenerated, sourceName]);

  return (
    <div className="relative">
      <input name={name} value={value} onChange={(e) => { setValue(e.target.value); setAutoGenerated(false); }} placeholder={placeholder} className={className} />
      {autoGenerated && value && (
        <span className="absolute -bottom-4 left-0 text-[10px] text-muted">auto-generated</span>
      )}
    </div>
  );
}
